'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SlotMachine_William.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aryll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aryll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Beedle() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Beedle", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property BeedleImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BeedleImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Deku_Leaf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Deku_Leaf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DinGem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DinGem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FaroreGem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FaroreGem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Floor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Link_Playing_Spirit_Flute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Link_Playing_Spirit_Flute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Link3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Link3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Link6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Link6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Medli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Medli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NayruGem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NayruGem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PinkRupee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PinkRupee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Princess_Zelda_Wind_Waker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Princess_Zelda_Wind_Waker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rubis_Argenté_SS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rubis_Argenté_SS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rubis_Rouge_SS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rubis_Rouge_SS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tetra1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tetra1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tetra2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tetra2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tetra3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tetra3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WindWaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WindWaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
